### ISSUE TITLE
Option to allow connections to Postgre from Vagrant host

### ISSUE THREAD

**Issue by faloi** [mumuki/escualo.rb#12]
When developing with the [devinstaller](https://github.com/mumuki/mumuki-devinstaller), it could be useful to have access to the Postgres DB (for instance, for running tests directly from the host machine).

To allow that, two small changes are needed:

**pg_hba.conf**
```bash
# Allow connections from Vagrant host on 10.0.2.2 to all databases
# for all users using an md5 hashed password
host    all         all         10.0.2.2/32    md5
```
**postgresql.conf**
```bash
listen_addresses='localhost'
```

I imagine that config could be placed when a flag like `--allow-vagrant-connections` is given to the plugin.

**Comment by flbulgarelli** [comment]
Related to https://github.com/mumuki/mumuki-platform/issues/305

**Comment by flbulgarelli** [comment]
Won't fix. Devinstaller is now deprecated
